# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
#      MAVEN_OPTS: -Xmx2600m
      pg_url: jdbc:postgresql://localhost/test?currentSchema=public&username=circleci&password=test
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # run tests!
      - run: 
          name: FullTest
          command: mvn -B install verify jacoco:report coveralls:report -DrepoToken=vjYKlpLcJdaVfbCnGi3gRp4f9dU89hpnm  
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
